### ISSUE TITLE
npx nx-ignore fails with Error: Cannot find module 'nx/presets/npm.json'

### ISSUE THREAD

**Issue by rtman** [nrwl/nx-labs#131]
Not really sure what the issue is here, this is straight from the guide on how to deploy nx with vercel. Does anyone know whats going on here? For reference this is a package-based nx monorepo using latest nx version.

```
Running "npx nx-ignore loyalty-admin --verbose"
15:02:49.100 | npm WARN exec The following package was not found and will be installed: nx-ignore@15.3.1
15:03:03.469 | node:internal/modules/cjs/loader:998
15:03:03.470 | throw err;
15:03:03.470 | ^
15:03:03.470 |  
15:03:03.470 | Error: Cannot find module 'nx/presets/npm.json'
15:03:03.470 | Require stack:
15:03:03.470 | - /vercel/.npm/_npx/cf7fc04e3df2a243/node_modules/nx/src/config/workspaces.js
15:03:03.471 | - /vercel/.npm/_npx/cf7fc04e3df2a243/node_modules/nx/src/project-graph/file-utils.js
15:03:03.471 | - /vercel/.npm/_npx/cf7fc04e3df2a243/node_modules/nx/src/project-graph/build-dependencies/typescript-import-locator.js
15:03:03.471 | - /vercel/.npm/_npx/cf7fc04e3df2a243/node_modules/nx/src/project-graph/build-dependencies/explicit-project-dependencies.js
15:03:03.471 | - /vercel/.npm/_npx/cf7fc04e3df2a243/node_modules/nx/src/project-graph/build-dependencies/index.js
15:03:03.471 | - /vercel/.npm/_npx/cf7fc04e3df2a243/node_modules/nx/src/project-graph/build-project-graph.js
15:03:03.471 | - /vercel/.npm/_npx/cf7fc04e3df2a243/node_modules/nx/src/project-graph/project-graph.js
15:03:03.471 | - /vercel/.npm/_npx/cf7fc04e3df2a243/node_modules/nx-ignore/src/index.js
15:03:03.472 | at Module._resolveFilename (node:internal/modules/cjs/loader:995:15)
15:03:03.472 | at Function.resolve (node:internal/modules/cjs/helpers:109:19)
15:03:03.472 | at Workspaces.readNxJson (/vercel/.npm/_npx/cf7fc04e3df2a243/node_modules/nx/src/config/workspaces.js:166:52)
15:03:03.472 | at readNxJson (/vercel/.npm/_npx/cf7fc04e3df2a243/node_modules/nx/src/config/configuration.js:7:72)
15:03:03.472 | at Object.<anonymous> (/vercel/.npm/_npx/cf7fc04e3df2a243/node_modules/nx/src/daemon/client/client.js:271:72)
15:03:03.472 | at Module._compile (node:internal/modules/cjs/loader:1159:14)
15:03:03.472 | at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
15:03:03.473 | at Module.load (node:internal/modules/cjs/loader:1037:32)
15:03:03.473 | at Module._load (node:internal/modules/cjs/loader:878:12)
15:03:03.473 | at Module.require (node:internal/modules/cjs/loader:1061:19) {
15:03:03.473 | code: 'MODULE_NOT_FOUND',
15:03:03.473 | requireStack: [
15:03:03.473 | '/vercel/.npm/_npx/cf7fc04e3df2a243/node_modules/nx/src/config/workspaces.js',
15:03:03.474 | '/vercel/.npm/_npx/cf7fc04e3df2a243/node_modules/nx/src/project-graph/file-utils.js',
15:03:03.474 | '/vercel/.npm/_npx/cf7fc04e3df2a243/node_modules/nx/src/project-graph/build-dependencies/typescript-import-locator.js',
15:03:03.474 | '/vercel/.npm/_npx/cf7fc04e3df2a243/node_modules/nx/src/project-graph/build-dependencies/explicit-project-dependencies.js',
15:03:03.474 | '/vercel/.npm/_npx/cf7fc04e3df2a243/node_modules/nx/src/project-graph/build-dependencies/index.js',
15:03:03.475 | '/vercel/.npm/_npx/cf7fc04e3df2a243/node_modules/nx/src/project-graph/build-project-graph.js',
15:03:03.475 | '/vercel/.npm/_npx/cf7fc04e3df2a243/node_modules/nx/src/project-graph/project-graph.js',
15:03:03.475 | '/vercel/.npm/_npx/cf7fc04e3df2a243/node_modules/nx-ignore/src/index.js'
15:03:03.475 | ]
15:03:03.475 | }

```

**Comment by jaysoo** [comment]
Updated the package so ensure that Nx is installed at the right version in the project before trying to use it. Thanks for reporting the issue!
