### ISSUE TITLE
nx-ignore on vercel fails by printing nx-affected help documentation

### ISSUE THREAD

**Issue by zgagnon** [nrwl/nx-labs#137]
My ignore build command is set to `npx nx-ignore <relavent-project> --verbose`. Command fails twice, printing out the help
for nx affected both times. Other errors as well. Please see logs from run.

```
[17:55:14.862] Cloning github.com/<redacted> (Branch:<redacted>, Commit: 7ba0c87)
[17:55:14.872] Skipping build cache since Vercel CLI used --force option
[17:55:16.844] Cloning completed: 1.981s
[17:55:16.844] Running "npx nx-ignore <redacted> --verbose"
[17:55:17.867] npm WARN exec The following package was not found and will be installed: nx-ignore@15.5.3
[17:55:18.420] ≫ Using Nx to determine if this project (<redacted>) is affected by the commit...
[17:55:18.421] ≫ Running from /vercel/.npm/_npx/cf7fc04e3df2a243/node_modules/nx-ignore/src
[17:55:18.421] ≫ Workspace root is /vercel/path0
[17:55:24.332] ≫ Found Nx at version 15.2.1
[17:55:24.332] 
[17:55:24.333] ≫ Validating base ref: 7ba0c87e5ec7ab72e61eed044962dcbd6ab91403
[17:55:24.333] 
[17:55:24.338] 
[17:55:24.338] ≫ Comparing 7ba0c87e5ec7ab72e61eed044962dcbd6ab91403...HEAD
[17:55:24.338] 
[17:55:25.239] nx print-affected
[17:55:25.239] 
[17:55:25.240] Prints information about the projects and targets affected by changes
[17:55:25.240] 
[17:55:25.240] Run command using --base=[SHA1] (affected by the committed, uncommitted and untracked changes):
[17:55:25.240]   --base  Base of the current branch (usually main)  [string]
[17:55:25.240] 
[17:55:25.240] or using --base=[SHA1] --head=[SHA2] (affected by the committed changes):
[17:55:25.241]   --base  Base of the current branch (usually main)  [string]
[17:55:25.241]   --head  Latest commit of the current branch (usually HEAD)  [string]
[17:55:25.241] 
[17:55:25.241] or using:
[17:55:25.241]   --files        Change the way Nx is calculating the affected command by providing directly changed files, list of files delimited by commas  [array]
[17:55:25.241]   --uncommitted  Uncommitted changes  [boolean]
[17:55:25.241]   --untracked    Untracked changes  [boolean]
[17:55:25.242] 
[17:55:25.242] Options:
[17:55:25.242]   --help     Show help  [boolean]
[17:55:25.242]   --version  Show version number  [boolean]
[17:55:25.242]   --select   Select the subset of the returned json document (e.g., --select=projects)  [string]
[17:55:25.242]   --type     Select the type of projects to be returned (e.g., --type=app)  [string] [choices: "app", "lib"]
[17:55:25.242]   --target   Task to run for affected projects  [string]
[17:55:25.243]   --exclude  Exclude certain projects from being processed  [array] [default: []]
[17:55:25.243]   --all      All projects  [boolean]
[17:55:25.243] 
[17:55:25.243] Examples:
[17:55:25.243]   print-affected                                               Print information about affected projects and the project graph
[17:55:25.244]   print-affected --base=main --head=HEAD                       Print information about the projects affected by the changes between main and HEAD (e.g,. PR)
[17:55:25.244]   print-affected --target=test                                 Prints information about the affected projects and a list of tasks to test them
[17:55:25.244]   print-affected --target=build --select=projects              Prints the projects property from the print-affected output
[17:55:25.244]   print-affected --target=build --select=tasks.target.project  Prints the tasks.target.project property from the print-affected output
[17:55:25.244] 
[17:55:25.245] Find more information and examples at https://nx.dev/nx/print-affected
[17:55:25.245] 
[17:55:25.245] Error: Cannot find module '@nrwl/workspace/presets/npm.json'
[17:55:25.245] Require stack:
[17:55:25.245] - /vercel/path0/node_modules/nx/src/config/workspaces.js
[17:55:25.245] - /vercel/path0/node_modules/nx/src/project-graph/file-utils.js
[17:55:25.245] - /vercel/path0/node_modules/nx/src/command-line/affected.js
[17:55:25.246] - /vercel/path0/node_modules/nx/src/command-line/nx-commands.js
[17:55:25.246] - /vercel/path0/node_modules/nx/bin/init-local.js
[17:55:25.246] - /vercel/path0/node_modules/nx/bin/nx.js
[17:55:25.246]     at Module._resolveFilename (node:internal/modules/cjs/loader:995:15)
[17:55:25.246]     at Function.resolve (/vercel/path0/node_modules/v8-compile-cache/v8-compile-cache.js:164:23)
[17:55:25.246]     at Workspaces.readNxJson (/vercel/path0/node_modules/nx/src/config/workspaces.js:168:52)
[17:55:25.247]     at readNxJson (/vercel/path0/node_modules/nx/src/config/configuration.js:7:72)
[17:55:25.247]     at Object.<anonymous> (/vercel/path0/node_modules/nx/src/daemon/client/client.js:288:72)
[17:55:25.247]     at Module._compile (/vercel/path0/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
[17:55:25.247]     at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
[17:55:25.247]     at Module.load (node:internal/modules/cjs/loader:1037:32)
[17:55:25.248]     at Module._load (node:internal/modules/cjs/loader:878:12)
[17:55:25.248]     at Module.require (node:internal/modules/cjs/loader:1061:19) {
[17:55:25.248]   code: 'MODULE_NOT_FOUND',
[17:55:25.248]   requireStack: [
[17:55:25.248]     '/vercel/path0/node_modules/nx/src/config/workspaces.js',
[17:55:25.248]     '/vercel/path0/node_modules/nx/src/project-graph/file-utils.js',
[17:55:25.249]     '/vercel/path0/node_modules/nx/src/command-line/affected.js',
[17:55:25.249]     '/vercel/path0/node_modules/nx/src/command-line/nx-commands.js',
[17:55:25.249]     '/vercel/path0/node_modules/nx/bin/init-local.js',
[17:55:25.249]     '/vercel/path0/node_modules/nx/bin/nx.js'
[17:55:25.249]   ]
[17:55:25.249] }
[17:55:25.250] node:internal/errors:863
[17:55:25.250]   const err = new Error(message);
[17:55:25.250]               ^
[17:55:25.250] 
[17:55:25.251] Error: Command failed: npx nx print-affected --base=7ba0c87e5ec7ab72e61eed044962dcbd6ab91403 --head=HEAD
[17:55:25.251] nx print-affected
[17:55:25.251] 
[17:55:25.251] Prints information about the projects and targets affected by changes
[17:55:25.253] 
[17:55:25.253] Run command using --base=[SHA1] (affected by the committed, uncommitted and untracked changes):
[17:55:25.254]   --base  Base of the current branch (usually main)  [string]
[17:55:25.254] 
[17:55:25.254] or using --base=[SHA1] --head=[SHA2] (affected by the committed changes):
[17:55:25.254]   --base  Base of the current branch (usually main)  [string]
[17:55:25.255]   --head  Latest commit of the current branch (usually HEAD)  [string]
[17:55:25.255] 
[17:55:25.255] or using:
[17:55:25.255]   --files        Change the way Nx is calculating the affected command by providing directly changed files, list of files delimited by commas  [array]
[17:55:25.255]   --uncommitted  Uncommitted changes  [boolean]
[17:55:25.256]   --untracked    Untracked changes  [boolean]
[17:55:25.256] 
[17:55:25.256] Options:
[17:55:25.256]   --help     Show help  [boolean]
[17:55:25.256]   --version  Show version number  [boolean]
[17:55:25.257]   --select   Select the subset of the returned json document (e.g., --select=projects)  [string]
[17:55:25.257]   --type     Select the type of projects to be returned (e.g., --type=app)  [string] [choices: "app", "lib"]
[17:55:25.257]   --target   Task to run for affected projects  [string]
[17:55:25.257]   --exclude  Exclude certain projects from being processed  [array] [default: []]
[17:55:25.257]   --all      All projects  [boolean]
[17:55:25.257] 
[17:55:25.258] Examples:
[17:55:25.258]   print-affected                                               Print information about affected projects and the project graph
[17:55:25.258]   print-affected --base=main --head=HEAD                       Print information about the projects affected by the changes between main and HEAD (e.g,. PR)
[17:55:25.258]   print-affected --target=test                                 Prints information about the affected projects and a list of tasks to test them
[17:55:25.259]   print-affected --target=build --select=projects              Prints the projects property from the print-affected output
[17:55:25.259]   print-affected --target=build --select=tasks.target.project  Prints the tasks.target.project property from the print-affected output
[17:55:25.260] 
[17:55:25.260] Find more information and examples at https://nx.dev/nx/print-affected
[17:55:25.260] 
[17:55:25.260] Error: Cannot find module '@nrwl/workspace/presets/npm.json'
[17:55:25.260] Require stack:
[17:55:25.260] - /vercel/path0/node_modules/nx/src/config/workspaces.js
[17:55:25.261] - /vercel/path0/node_modules/nx/src/project-graph/file-utils.js
[17:55:25.261] - /vercel/path0/node_modules/nx/src/command-line/nx-commands.js
[17:55:25.262] - /vercel/path0/node_modules/nx/bin/init-local.js
[17:55:25.262] - /vercel/path0/node_modules/nx/bin/nx.js
[17:55:25.262]     at Module._resolveFilename (node:internal/modules/cjs/loader:995:15)
[17:55:25.262]     at Function.resolve (/vercel/path0/node_modules/v8-compile-cache/v8-compile-cache.js:164:23)
[17:55:25.262]     at Workspaces.readNxJson (/vercel/path0/node_modules/nx/src/config/workspaces.js:168:52)
[17:55:25.262]     at readNxJson (/vercel/path0/node_modules/nx/src/config/configuration.js:7:72)
[17:55:25.262]     at Object.<anonymous> (/vercel/path0/node_modules/nx/src/daemon/client/client.js:288:72)
[17:55:25.263]     at Module._compile (/vercel/path0/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
[17:55:25.263]     at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
[17:55:25.263]     at Module.load (node:internal/modules/cjs/loader:1037:32)
[17:55:25.263]     at Module._load (node:internal/modules/cjs/loader:878:12)
[17:55:25.263]     at Module.require (node:internal/modules/cjs/loader:1061:19) {
[17:55:25.263]   code: 'MODULE_NOT_FOUND',
[17:55:25.263]   requireStack: [
[17:55:25.263]     '/vercel/path0/node_modules/nx/src/config/workspaces.js',
[17:55:25.264]     '/vercel/path0/node_modules/nx/src/project-graph/file-utils.js',
[17:55:25.264]     '/vercel/path0/node_modules/nx/src/command-line/affected.js',
[17:55:25.264]     '/vercel/path0/node_modules/nx/src/command-line/nx-commands.js',
[17:55:25.264]     '/vercel/path0/node_modules/nx/bin/init-local.js',
[17:55:25.264]     '/vercel/path0/node_modules/nx/bin/nx.js'
[17:55:25.264]   ]
[17:55:25.264] }
[17:55:25.264] 
[17:55:25.264]     at checkExecSyncError (node:child_process:871:11)
[17:55:25.264]     at execSync (node:child_process:943:15)
[17:55:25.265]     at /vercel/.npm/_npx/cf7fc04e3df2a243/node_modules/nx-ignore/src/index.js:57:24
[17:55:25.265]     at Generator.next (<anonymous>)
[17:55:25.265]     at asyncGeneratorStep (/vercel/.npm/_npx/cf7fc04e3df2a243/node_modules/@swc/helpers/lib/_async_to_generator.js:13:28)
[17:55:25.265]     at _next (/vercel/.npm/_npx/cf7fc04e3df2a243/node_modules/@swc/helpers/lib/_async_to_generator.js:31:17)
[17:55:25.265]     at /vercel/.npm/_npx/cf7fc04e3df2a243/node_modules/@swc/helpers/lib/_async_to_generator.js:36:13
[17:55:25.265]     at new Promise (<anonymous>)
[17:55:25.265]     at /vercel/.npm/_npx/cf7fc04e3df2a243/node_modules/@swc/helpers/lib/_async_to_generator.js:28:16 {
[17:55:25.266]   status: 1,
[17:55:25.266]   signal: null,
[17:55:25.266]   output: [
[17:55:25.266]     null,
[17:55:25.267]     Buffer(0) [Uint8Array] [],
[17:55:25.267]     Buffer(3583) [Uint8Array] [
[17:55:25.267]       110, 120,  32, 112, 114, 105, 110, 116,  45,  97, 102, 102,
[17:55:25.268]       101,  99, 116, 101, 100,  10,  10,  80, 114, 105, 110, 116,
[17:55:25.268]       115,  32, 105, 110, 102, 111, 114, 109,  97, 116, 105, 111,
[17:55:25.268]       110,  32,  97,  98, 111, 117, 116,  32, 116, 104, 101,  32,
[17:55:25.268]       112, 114, 111, 106, 101,  99, 116, 115,  32,  97, 110, 100,
[17:55:25.268]        32, 116,  97, 114, 103, 101, 116, 115,  32,  97, 102, 102,
[17:55:25.268]       101,  99, 116, 101, 100,  32,  98, 121,  32,  99, 104,  97,
[17:55:25.268]       110, 103, 101, 115,  10,  10,  82, 117, 110,  32,  99, 111,
[17:55:25.268]       109, 109,  97, 110,
[17:55:25.269]       ... 3483 more items
[17:55:25.269]     ]
[17:55:25.269]   ],
[17:55:25.269]   pid: 319,
[17:55:25.269]   stdout: Buffer(0) [Uint8Array] [],
[17:55:25.269]   stderr: Buffer(3583) [Uint8Array] [
[17:55:25.269]     110, 120,  32, 112, 114, 105, 110, 116,  45,  97, 102, 102,
[17:55:25.269]     101,  99, 116, 101, 100,  10,  10,  80, 114, 105, 110, 116,
[17:55:25.269]     115,  32, 105, 110, 102, 111, 114, 109,  97, 116, 105, 111,
[17:55:25.269]     110,  32,  97,  98, 111, 117, 116,  32, 116, 104, 101,  32,
[17:55:25.270]     112, 114, 111, 106, 101,  99, 116, 115,  32,  97, 110, 100,
[17:55:25.270]      32, 116,  97, 114, 103, 101, 116, 115,  32,  97, 102, 102,
[17:55:25.270]     101,  99, 116, 101, 100,  32,  98, 121,  32,  99, 104,  97,
[17:55:25.270]     110, 103, 101, 115,  10,  10,  82, 117, 110,  32,  99, 111,
[17:55:25.270]     109, 109,  97, 110,
[17:55:25.270]     ... 3483 more items
[17:55:25.270]   ]
[17:55:25.270] }
[17:55:25.271] 
[17:55:25.271] Node.js v18.12.1
[17:55:27.851] Running "vercel build"
[17:55:28.459] Vercel CLI 28.12.7
[17:55:30.278] Detected `pnpm-lock.yaml` generated by pnpm 7...
[17:55:30.286] Running "install" command: `pnpm install`...
[17:55:31.116] Lockfile is up to date, resolution step is skipped
[17:55:31.391] Progress: resolved 1, reused 0, downloaded 0, added 0
[17:55:32.125] Packages: +2559
[17:55:32.126] ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
[17:55:32.418] Progress: resolved 2559, reused 0, downloaded 0, added 0
[17:55:32.952] Packages are hard linked from the content-addressable store to the virtual store.
[17:55:32.952]   Content-addressable store is at: /vercel/.local/share/pnpm/store/v3
[17:55:32.953]   Virtual store is at:             node_modules/.pnpm
[17:55:33.432] Progress: resolved 2559, reused 0, downloaded 32, added 29
[17:55:34.452] Progress: resolved 2559, reused 0, downloaded 72, added 67
[17:55:35.459] Progress: resolved 2559, reused 0, downloaded 82, added 81
[17:55:36.476] Progress: resolved 2559, reused 0, downloaded 111, added 108
[17:55:37.479] Progress: resolved 2559, reused 0, downloaded 158, added 154
[17:55:38.486] Progress: resolved 2559, reused 0, downloaded 197, added 199
[17:55:39.491] Progress: resolved 2559, reused 0, downloaded 229, added 232
[17:55:40.497] Progress: resolved 2559, reused 0, downloaded 275, added 273
[17:55:41.498] Progress: resolved 2559, reused 0, downloaded 330, added 329
[17:55:42.505] Progress: resolved 2559, reused 0, downloaded 371, added 370
[17:55:43.506] Progress: resolved 2559, reused 0, downloaded 398, added 396
[17:55:44.510] Progress: resolved 2559, reused 0, downloaded 444, added 435
[17:55:45.517] Progress: resolved 2559, reused 0, downloaded 468, added 468

... Build continues as normal
```

**Comment by zgagnon** [comment]
Thanks!
