### ISSUE TITLE
Cannot add remix to existing workspace

### ISSUE THREAD

**Issue by jbojcic1** [nrwl/nx-labs#148]
I have an existing nx workspace with several next.js apps and I wanted to add a remix app too now. However when I run `npx nx g @nrwl/remix:setup --verbose` as suggested in the installation steps I am getting the following error:
```
 >  NX   (0 , project_configuration_1.shouldDefaultToUsingStandaloneConfigs) is not a function


TypeError: (0 , project_configuration_1.shouldDefaultToUsingStandaloneConfigs) is not a function
    at getWorkspaceLayout (/Users/jbojcic/Projects/.../node_modules/.pnpm/@nrwl+devkit@14.8.6_nx@15.7.0+typescript@4.9.5/node_modules/@nrwl/devkit/src/utils/get-workspace-layout.js:25:96)
    at /Users/jbojcic/Projects/.../node_modules/.pnpm/@nrwl+remix@14.7.0_ffbz3dot37la745pgzrxjp57fi/node_modules/@nrwl/remix/src/generators/setup/setup.impl.js:8:61
    at Generator.next (<anonymous>)
    at /Users/jbojcic/Projects/.../node_modules/.pnpm/tslib@2.5.0/node_modules/tslib/tslib.js:167:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/Users/jbojcic/Projects/.../node_modules/.pnpm/tslib@2.5.0/node_modules/tslib/tslib.js:163:16)
    at default_1 (/Users/jbojcic/Projects/.../node_modules/.pnpm/@nrwl+remix@14.7.0_ffbz3dot37la745pgzrxjp57fi/node_modules/@nrwl/remix/src/generators/setup/setup.impl.js:7:20)
    at Object.<anonymous> (/Users/jbojcic/Projects/.../node_modules/.pnpm/nx@15.7.0_v2zqmz37psxnzhtp5j6kitlanu/node_modules/nx/src/command-line/generate.js:250:36)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/jbojcic/Projects/.../node_modules/.pnpm/tslib@2.5.0/node_modules/tslib/tslib.js:164:62)
```

My package manager is pnpm and my nx version is 15.7.0, @nrwl/remix version is 14.7.0

**Comment by eriktim** [comment]
Same issue as https://github.com/nxext/nx-extensions/issues/902?

**Comment by mandarini** [comment]
Related: https://github.com/nrwl/nx-labs/issues/145, https://github.com/nrwl/nx-labs/issues/164

**Comment by philipjfulcher** [comment]
You should see a new version of the `@nrwl/remix` plugin soon which resolves this.
