### ISSUE TITLE
Deno application build fails for the default generated app

### ISSUE THREAD

**Issue by AdditionAddict** [nrwl/nx-labs#228]
I'm getting error

```
> nx run inventory-deno:build

Using deno_emit to build apps/inventory-deno/src/main.ts (https://deno.land/x/emit)
error: Uncaught (in promise) Error: Unable to output during bundling.
      const ret = new Error(getStringFromWasm0(arg0, arg1));
                  ^
    at __wbg_new_651776e932b7e9c7 (https://deno.land/x/emit@0.20.0/lib/emit.generated.js:329:19)
    at <anonymous> (https://deno.land/x/emit@0.20.0/lib/emit_bg.wasm:1:7327615)
    at <anonymous> (https://deno.land/x/emit@0.20.0/lib/emit_bg.wasm:1:1167558)
    at <anonymous> (https://deno.land/x/emit@0.20.0/lib/emit_bg.wasm:1:6436132)
    at <anonymous> (https://deno.land/x/emit@0.20.0/lib/emit_bg.wasm:1:7289320)
    at __wbg_adapter_16 (https://deno.land/x/emit@0.20.0/lib/emit.generated.js:205:6)
    at real (https://deno.land/x/emit@0.20.0/lib/emit.generated.js:189:14)
    at eventLoopTick (ext:core/01_core.js:165:11)
```

nx report
```
 >  NX   Report complete - copy this into the issue template

   Node : 16.17.1
   OS   : win32 x64
   pnpm : 8.1.0

   nx                      : 15.9.2
   @nrwl/js                : 15.9.2
   @nrwl/jest              : 15.9.2
   @nrwl/linter            : 15.9.2
   @nrwl/workspace         : 15.9.2
   @nrwl/angular           : 15.9.2
   @nrwl/cli               : 15.9.2
   @nrwl/cypress           : 15.9.2
   @nrwl/devkit            : 15.9.2
   @nrwl/esbuild           : 15.9.2
   @nrwl/eslint-plugin-nx  : 15.9.2
   @nrwl/node              : 15.9.2
   @nrwl/storybook         : 15.9.2
   @nrwl/tao               : 15.9.2
   @nrwl/web               : 15.9.2
   @nrwl/webpack           : 15.9.2
   @nrwl/nx-cloud          : 15.3.5
   typescript              : 4.9.5
   ---------------------------------------
   Community plugins:
   @ngrx/component-store : 15.4.0
   @ngrx/effects         : 15.4.0
   @ngrx/entity          : 15.4.0
   @ngrx/router-store    : 15.4.0
   @ngrx/store           : 15.4.0
   @ngrx/store-devtools  : 15.4.0
   @nrwl/deno            : 15.9.6
   @storybook/angular    : 7.0.2
   nx-cloud              : 15.3.5
```

**Comment by barbados-clemens** [comment]
This looks to be an issue with deno_emit on windows. As on MacOS it doesn't error. and removing all of Nx related configurations still produces the same error

Example Repo without Nx: https://github.com/barbados-clemens/deno-build-test

```shell
PS C:\Users\caleb\code\sandbox\deno-build-test> deno run --allow-all .\deno-emit.ts
error: Uncaught (in promise) Error: Unable to output during bundling.
      const ret = new Error(getStringFromWasm0(arg0, arg1));
                  ^
    at __wbg_new_87297f22973157c8 (https://deno.land/x/emit@0.24.0/emit.generated.js:509:19)
    at <anonymous> (file:///C:/Users/caleb/AppData/Local/deno-wasmbuild/9da37c1955ad9ccc04d9f3aaa76f4ee03ea13face7dcc7bbc42752ce7eb21a53.wasm:1:7369575)
    at <anonymous> (file:///C:/Users/caleb/AppData/Local/deno-wasmbuild/9da37c1955ad9ccc04d9f3aaa76f4ee03ea13face7dcc7bbc42752ce7eb21a53.wasm:1:1541216)
    at <anonymous> (file:///C:/Users/caleb/AppData/Local/deno-wasmbuild/9da37c1955ad9ccc04d9f3aaa76f4ee03ea13face7dcc7bbc42752ce7eb21a53.wasm:1:6482348)
    at <anonymous> (file:///C:/Users/caleb/AppData/Local/deno-wasmbuild/9da37c1955ad9ccc04d9f3aaa76f4ee03ea13face7dcc7bbc42752ce7eb21a53.wasm:1:7329815)
    at __wbg_adapter_46 (https://deno.land/x/emit@0.24.0/emit.generated.js:241:6)
    at real (https://deno.land/x/emit@0.24.0/emit.generated.js:225:14)
    at eventLoopTick (ext:core/01_core.js:181:11)
```
