### ISSUE TITLE
Metro Bundler resolve undefined Error

### ISSUE THREAD

**Issue by bnuby** [nrwl/nx-labs#30]
Machine Info

OS: macOS Monterey 12.2.1 
node version: v16.14.0
react native:    0.64.3
react: 17.0.1
@nrwl/expo: 13.9.0

env: Development

It appears  everytime the apps fetch file from the server

execute script: nx serve myapp:run-android

To clear this warning, run:
`watchman watch-del '/Users/x/Workspace/react/nx/react-x-native' ; watchman watch-project '/Users/x/Workspace/react/nx/react-x-native'`

Unrecognized event: {"type":"transformer_load_started"}
Unrecognized event: {"type":"transformer_load_done"}
Started Metro Bundler
Error: Cannot resolve undefined
    at tsconfigPathsResolver (/Users/someone/workfiles/react/nx/react-x-native/packages/expo/plugins/metro-resolver.ts:149:11)
    at /Users/someone/workfiles/react/nx/react-x-native/packages/expo/plugins/metro-resolver.ts:47:12
    at Object.resolve (/Users/someone/workfiles/react/nx/react-x-native/node_modules/metro-resolver/src/resolve.js:31:12)
    at ModuleResolver.resolveDependency (/Users/someone/workfiles/react/nx/react-x-native/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:115:31)
    at DependencyGraph.resolveDependency (/Users/someone/workfiles/react/nx/react-x-native/node_modules/metro/src/node-haste/DependencyGraph.js:231:43)
    at /Users/someone/workfiles/react/nx/react-x-native/node_modules/metro/src/lib/transformHelpers.js:129:24
    at Server._resolveRelativePath (/Users/someone/workfiles/react/nx/react-x-native/node_modules/metro/src/Server.js:1107:12)
    at Server.requestProcessor [as _processBundleRequest] (/Users/someone/workfiles/react/nx/react-x-native/node_modules/metro/src/Server.js:450:37)
    at Server._processRequest (/Users/someone/workfiles/react/nx/react-x-native/node_modules/metro/src/Server.js:406:9)

**Comment by xiongemi** [comment]
i could not replicate this issue. could you upgrade to the latest @nrwl/expo by running `nx migrate @nrwl/expo` and try again.
