### ISSUE TITLE
TypeError: plugin.startsWith is not a function

### ISSUE THREAD

**Issue by tult98** [nrwl/nx-labs#373]
Node: v20.11.0
nx-ignore@17.2.8

I'm trying to set up remote caching for Nx on Vercel but end up with this error when running `npx nx-ignore <project-name>` with this setting.

<img width="941" alt="image" src="https://github.com/nrwl/nx-labs/assets/29749097/93f8985f-98a8-4bd8-a83b-4b5b065dc60d">

Here is the full log from Vercel 
```
[15:13:53.260] Running "npx nx-ignore web"
[15:13:54.160] npm WARN exec The following package was not found and will be installed: nx-ignore@17.2.8
[15:13:54.603] ≫ Using Nx to determine if this project (web) is affected by the commit...
[15:13:54.607] /vercel/.npm/_npx/cf7fc04e3df2a243/node_modules/nx-ignore/src/index.js:83
[15:13:54.607]     return (_nxJson_plugins_filter = (_nxJson_plugins = nxJson.plugins) == null ? void 0 : _nxJson_plugins.filter((plugin)=>!plugin.startsWith('.'))) != null ? _nxJson_plugins_filter : [];
[15:13:54.607]                                                                                                                                     ^
[15:13:54.607] 
[15:13:54.607] TypeError: plugin.startsWith is not a function
[15:13:54.608]     at /vercel/.npm/_npx/cf7fc04e3df2a243/node_modules/nx-ignore/src/index.js:83:133
[15:13:54.608]     at Array.filter (<anonymous>)
[15:13:54.608]     at findThirdPartyPlugins (/vercel/.npm/_npx/cf7fc04e3df2a243/node_modules/nx-ignore/src/index.js:83:108)
[15:13:54.608]     at main (/vercel/.npm/_npx/cf7fc04e3df2a243/node_modules/nx-ignore/src/index.js:39:71)
[15:13:54.608]     at Object.<anonymous> (/vercel/.npm/_npx/cf7fc04e3df2a243/node_modules/nx-ignore/src/index.js:27:1)
[15:13:54.608]     at Module._compile (node:internal/modules/cjs/loader:1376:14)
[15:13:54.608]     at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
[15:13:54.608]     at Module.load (node:internal/modules/cjs/loader:1207:32)
[15:13:54.608]     at Module._load (node:internal/modules/cjs/loader:1023:12)
[15:13:54.608]     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:135:12)
[15:13:54.608] 
[15:13:54.608] Node.js v20.11.0
[15:13:54.889] Running "vercel build"
[15:13:55.387] Vercel CLI 33.5.1
```

I've tried to run the command on my local machine M1 but still get that issue with both node v16 and v20.

**Comment by 3kumar** [comment]
We are also facing a similar issue. When we make a push the nx-ignore forces the deployment to fail. However, if we redeploy the same commit from Vercel dashboard, it gets built and deployed successfully.

Node.js @ v20.11.1
Vercel cli @33.6.2
pnpm @ 8.15.5
nx-ignore @ 18.0.2
nx@18.2.2
