### ISSUE TITLE
Issue with running basic @nx/rspack app in monorepo

### ISSUE THREAD

**Issue by samtsai** [nrwl/nx-labs#413]
Run `nx g @nx/rspack:app my-app --style=css`

See
```
 NX   Report complete - copy this into the issue template

Node           : 16.20.0
OS             : darwin-arm64
Native Target  : aarch64-macos
npm            : 8.19.4

nx (global)        : 19.5.6
nx                 : 19.5.7
@nx/js             : 19.5.7
@nx/jest           : 19.5.7
@nx/linter         : 19.5.7
@nx/eslint         : 19.5.7
@nx/workspace      : 19.5.7
@nx/cypress        : 19.5.7
@nx/devkit         : 19.5.7
@nx/eslint-plugin  : 19.5.7
@nx/react          : 19.5.7
@nrwl/tao          : 19.5.7
@nx/web            : 19.5.7
@nx/webpack        : 19.5.7
typescript         : 5.5.4
---------------------------------------
Registered Plugins:
@nx/rspack/plugin
---------------------------------------
Community plugins:
@nx/rspack : 19.5.0
---------------------------------------
⚠️ Unable to construct project graph.
Failed to process project graph. Run "nx reset" to fix this. Please report the issue if you keep seeing it.
Failed to process project graph. Run "nx reset" to fix this. Please report the issue if you keep seeing it.
  An error occurred while processing files for the @nx/rspack/plugin plugin.
    - rspack.config.js: Cannot read properties of undefined (reading 'nodes')
      TypeError: Cannot read properties of undefined (reading 'nodes')
          at makeConfig (/Users/satsai/Code/rusty/node_modules/@nx/rspack/src/utils/with-nx.js:15:46)
          at /Users/satsai/Code/rusty/node_modules/@nx/rspack/src/utils/config.js:16:32
          at Generator.next (<anonymous>)
          at fulfilled (/Users/satsai/Code/rusty/node_modules/tslib/tslib.js:166:62)
          at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Comment by samtsai** [comment]
Seems similar to: https://github.com/nrwl/nx/issues/26303

**Comment by samtsai** [comment]
Actually looks like #408 is the issue
